apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_BD
          value: "kubenews"
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"

---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 10
  selector:
    #replicas: 10
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: marod12/kube-news:{{TAG}}
          ports:
          - containerPort: 8080
          env:
          - name: DB_HOST
            value: "postgre"  #nome do service
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
  type: LoadBalancer
