FROM node:20.10.0-alpine3.19
RUN apk update && apk add --no-cache curl=8.9.1-r1
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.49.1
ADD --chown=nobody:nogroup --chmod=777 https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 /usr/local/bin/hadolint
USER node
WORKDIR /app
EXPOSE 8080
CMD ["tail", "-f", "/dev/null"]