services:
  kubenews:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    volumes: 
      - .:/app:cached  # para ter mais performance, o normal é .:/app

  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    depends_on:
      - kubenews
    volumes:
      - .docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - kubenews-net