services:
  kubenews:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    volumes: 
      - .:/app:cached  # para ter mais performance, o normal é .:/app

  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 9090:9090
    depends_on:
      - kubenews
    volumes:
      - .docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - kubenews-net

  grafana:
    image: grafana/grafana:9.5.15
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - .docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - .docker/grafana/provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - .docker/grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - .docker/grafana/dashboard:/var/lib/grafana/dashboards
    networks:
      - kubenews-net