FROM node:20.10.0-alpine3.19
RUN apk update && apk add --no-cache curl
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.49.1
USER node
WORKDIR /app
EXPOSE 8080
CMD ["tail", "-f", "/dev/null"]